relative_permalinks: true
markdown: kramdown
title: Hands-on Exercises
exclude: [README.md, less]

# These allow the documentation to be updated with nerw releases
# of Spark, Scala, and Mesos.
AMI: ami-b70196de
SPARK_VERSION: 0.7.0
SPARK_VERSION_SHORT: 0.7.0
SCALA_VERSION: 2.9.2
MESOS_VERSION: 0.9.0-incubating
